CREATE DATABASE readme_db DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;

USE readme_db;

CREATE TABLE users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  creation_date DATETIME DEFAULT CURRENT_TIMESTAMP, 
  email VARCHAR(128) NOT NULL UNIQUE,
  login VARCHAR(128) NOT NULL UNIQUE,
  password CHAR(64) NOT NULL,
  avatar VARCHAR(128) NULL DEFAULT ''
);

CREATE TABLE posts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  author_id VARCHAR(128) NOT NULL,
  post_type_id VARCHAR(128) NOT NULL,
  title VARCHAR(128) NOT NULL,
  text TEXT NULL DEFAULT NULL,
  quote VARCHAR(128) NULL DEFAULT '',
  photo VARCHAR(128) NULL DEFAULT '',
  video VARCHAR(128) NULL DEFAULT '',
  link VARCHAR(128) NULL DEFAULT '',
  count_views INT NULL DEFAULT NULL
);

CREATE TABLE comments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  creation_date DATETIME DEFAULT CURRENT_TIMESTAMP, 
  content TEXT NOT NULL,
  author_id VARCHAR(128) NOT NULL,
  post_id INT NOT NULL
);

ALTER TABLE `comments` ADD FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `comments` ADD FOREIGN KEY (`post_id`) REFERENCES `posts`(`id`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE likes (
  author_id VARCHAR(128) NOT NULL,
  post_id INT NOT NULL
);

ALTER TABLE `likes` ADD FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `likes` ADD FOREIGN KEY (`post_id`) REFERENCES `posts`(`id`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE subscriptions (
  subscriber_id VARCHAR(128) NOT NULL,
  author_id VARCHAR(128) NOT NULL
);

ALTER TABLE `subscriptions` ADD FOREIGN KEY (`subscriber_id`) REFERENCES `users`(`id`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `subscriptions` ADD FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE messages (
  id INT AUTO_INCREMENT PRIMARY KEY,
  creation_date DATETIME DEFAULT CURRENT_TIMESTAMP,
  content TEXT NOT NULL,
  sender_id VARCHAR(128) NOT NULL,
  recipient_id VARCHAR(128) NOT NULL
);

ALTER TABLE `messages` ADD FOREIGN KEY (`sender_id`) REFERENCES `users`(`id`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `messages` ADD FOREIGN KEY (`recipient_id`) REFERENCES `users`(`id`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE hashtags (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL
);

CREATE TABLE post_types (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(128) NOT NULL,
  name VARCHAR(128) NOT NULL UNIQUE
);

ALTER TABLE `posts` ADD FOREIGN KEY (`author_id`) REFERENCES `users`(`id`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE `posts` ADD FOREIGN KEY (`post_type_id`) REFERENCES `post_types`(`id`) 
ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE INDEX p_post_type_id ON posts(post_type_id);

